version: "3.7"

services:
  
  book_keeper_db:
    image: mysql:8.0.21
    container_name: book_keeper_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_bookkeeper
      MYSQL_USER: wilson
      MYSQL_PASSWORD: password
    ports: 
      - 3306:3306
    volumes: 
      - ./SQL-scripts/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    links: 
      - book_keeper_db
    restart: always
    environment: 
      PMA_HOST: book_keeper_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports: 
      - 8080:80

  token_redis_db:
    image: redis:6.0.5-alpine3.12
    container_name: token_redis_db
    restart: always
    ports: 
      - 6379:6379
    volumes: 
      - ./Redis-config/redis_token.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  task_queue_redis_db:
    image: redis:6.0.5-alpine3.12
    container_name: task_queue_redis_db
    restart: always
    ports: 
      - 6380:6380
    volumes: 
      - ./Redis-config/redis_task_queue.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  task_queue_worker:
    build: ./Backend/
    container_name: task_queue_worker
    environment: 
      - PYTHONUNBUFFERED=1
    command: celery -A book_keeping_backend_package.celery_client worker --loglevel=info
    volumes:
      - ./Backend/:/opt/src/

  web:
    build: ./Backend/
    container_name: web
    environment: 
      - PYTHONUNBUFFERED=1
    # command: gunicorn --workers 15 --bind 0.0.0.0:5000 book_keeper_backend_api:app # for production environment
    command: flask run # for development
    ports: 
      - 5000:5000
    volumes: 
      - ./Backend/:/opt/src/

  nginx:
    build: ./nginx/
    container_name: nginx
    ports: 
      - 1337:80