version: "3.7"

services:
  
  book_keeper_db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_bookkeeper
      MYSQL_USER: wilson
      MYSQL_PASSWORD: password
    ports: 
      - 3306:3306
    volumes: 
      - ./SQL-scripts/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    links: 
      - book_keeper_db
    restart: always
    environment: 
      PMA_HOST: book_keeper_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports: 
      - 8080:80

  token_redis_db:
    image: redis:6.0.5-alpine3.12
    restart: always
    ports: 
      - 6379:6379
    volumes: 
      - ./Redis-config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
