matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd book-keeper-back-end
      script:
        - pip3 install -r requirements.txt
        - set PYTHONPATH=.
        - coverage run -m pytest
        - coverage report -m

    - language: node_js
      node_js:
        - 14
      before_script:
        - cd book-keeper-front-end
      script:
        - npm install
    - language: bash
      dist: xenial
      services:
        - docker
      before_script:
        - echo "123456789" | docker login -u "entao2000" --password-stdin
      script:
        - echo "test code"  
      after_success:
        - docker build -t username/alpine .
        - docker push username/alpine

notifications:
  email:
    - entao2000@gmail.com
    - wilsonwang2019@tamu.edu