matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd book-keeper-back-end
        - cd unit_test
      script:
        - python test_route.py

    - language: node_js
      node_ja:
        - 14
      before_script:
        - cd book-keeper-front-end
      script:
        - npm test

services:
  -docker

notifications:
  email:
    - entao2000@gmail.com
    - wilsonwang2019@tamu.edu