matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd book-keeper-back-end
        - cd unit_test
      script:
        - pip3 install -r requirements.txt
        - set PYTHONPATH=.
        - coverage run -m pytest
        - coverage report -m

    - language: node_js
      node_js:
        - 14
      before_script:
        - cd book-keeper-front-end
      script:
        - npm install

services:
  -docker

notifications:
  email:
    - entao2000@gmail.com
    - wilsonwang2019@tamu.edu