"""empty message

Revision ID: 0ed9c5a4bcc2
Revises: ed84677a41d1
Create Date: 2020-05-11 21:58:24.868199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed9c5a4bcc2'
down_revision = 'ed84677a41d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reimburse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=140), nullable=True),
    sa.Column('classification', sa.String(length=140), nullable=True),
    sa.Column('american_website_link', sa.String(length=512), nullable=True),
    sa.Column('item_website_link', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('delivery', sa.String(length=512), nullable=True),
    sa.Column('date_needed', sa.DateTime(), nullable=True),
    sa.Column('reason_to_purchase', sa.String(length=1024), nullable=True),
    sa.Column('recipient_photo_url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimburse_timestamp'), 'reimburse', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reimburse_timestamp'), table_name='reimburse')
    op.drop_table('reimburse')
    # ### end Alembic commands ###
